export { default as loginImg } from "./images/login_pg_img.jpg"
export { default as heroImg } from "./images/hero_pg_img.jpg"
export { default as dashboard_black } from "./images/dashboard_black.png"
export { default as dashboard_white } from "./images/dashboard_white.png"
export { default as aboutHeroImg } from "./images/about_hero_img.jpg"
export { default as aboutMissionImg } from "./images/about_mission_img.jpg"
export { default as aboutHeroImg2 } from "./images/about_hero_img2.svg"
// export { default as logoImg4 } from "./images/logo-4.jpg"
// export { default as logoImg5 } from "./images/logo-5.jpg"
// export { default as logoImg6 } from "./images/logo-6.jpg"
// export { default as logoImg7 } from "./images/logo-7.jpg"
// export { default as logoImg8 } from "./images/logo-8.jpg"
// export { default as logoImg9 } from "./images/logo-9.jpg"
// export { default as logoImg10 } from "./images/logo-10.jpg"
// export { default as logoImg11 } from "./images/logo-11.jpg"
// export { default as filesImg } from "./images/files-img.avif"